# Generated by Django 3.1.6 on 2021-02-02 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BEDTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_title', models.CharField(max_length=200, unique=True)),
                ('interaction_date', models.DateField()),
                ('lead_minister_or_official', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('city_or_town', models.CharField(max_length=200)),
                ('attending_organisations', models.TextField()),
                ('attending_contacts', models.TextField()),
            ],
        ),
    ]
