# Generated by Django 3.1.6 on 2021-02-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
