# Generated by Django 3.1.6 on 2021-02-03 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_auto_20210203_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
