# Generated by Django 3.1.6 on 2021-02-08 12:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0005_auto_20210205_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtemplate',
            name='city_or_town',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='country',
            field=django_countries.fields.CountryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='type',
            field=models.CharField(choices=[('bilateral_meeting', 'Bilateral Meeting'), ('brush_by', 'Brush By'), ('conference', 'Conference'), ('email', 'Email'), ('forum', 'Forum'), ('letter', 'Letter'), ('multilateral_meeting', 'Multilateral Meeting'), ('phone_call', 'Phone Call'), ('reception', 'Reception'), ('roadshow', 'Roadshow'), ('roundtable', 'Roundtable'), ('speech', 'Speech'), ('visit', 'Visit'), ('webinar', 'Webinar')], max_length=100),
        ),
    ]
