# Generated by Django 3.1.6 on 2021-02-08 14:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0006_auto_20210208_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtemplate',
            name='attending_contacts',
            field=models.TextField(help_text='A list of attendees (by e-mail address) who attended, separated by a comma.'),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='attending_organisations',
            field=models.TextField(help_text='A list of organisations who attended, separated by a comma.'),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='city_or_town',
            field=models.CharField(help_text='For example Bristol, Brighton or Chelmsford.', max_length=200),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='country',
            field=django_countries.fields.CountryField(help_text='Please select from the list below.', max_length=200),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='interaction_date',
            field=models.DateField(help_text='The date of the interaction, in a yyyy-mm-dd format.'),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='interaction_title',
            field=models.CharField(help_text='This is the title of the interaction, for example "XYZ meeting"', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='lead_minister_or_official',
            field=models.EmailField(help_text='The e-mail address of the minister or official who led the engagement.', max_length=254),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='region',
            field=models.CharField(choices=[('london', 'London'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('northern_ireland', 'Northern Ireland'), ('east_of_england', 'East of England'), ('east_midlands', 'East Midlands'), ('north_east', 'North East'), ('south_east', 'South East'), ('south_west', 'South West'), ('west_midlands', 'West Midlands'), ('yorkshire_and_the_humber', 'Yorkshire and the Humber'), ('guernsey', 'Guernsey'), ('jersey', 'Jersey'), ('isle_of_man', 'Isle of Man'), ('non_uk', 'Non UK')], help_text='Please select from the list below.', max_length=200),
        ),
        migrations.AlterField(
            model_name='bedtemplate',
            name='type',
            field=models.CharField(choices=[('bilateral_meeting', 'Bilateral Meeting'), ('brush_by', 'Brush By'), ('conference', 'Conference'), ('email', 'Email'), ('forum', 'Forum'), ('letter', 'Letter'), ('multilateral_meeting', 'Multilateral Meeting'), ('phone_call', 'Phone Call'), ('reception', 'Reception'), ('roadshow', 'Roadshow'), ('roundtable', 'Roundtable'), ('speech', 'Speech'), ('visit', 'Visit'), ('webinar', 'Webinar')], help_text='See guidance for examples of types.', max_length=200),
        ),
    ]
