# Generated by Django 3.1.6 on 2021-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0007_auto_20210208_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtemplate',
            name='country',
            field=models.CharField(choices=[('united_kingdom', 'United Kingdom'), ('germany', 'Germany'), ('united_states_of_america', 'United States of America')], help_text='Please select from the list below.', max_length=200),
        ),
    ]
